In [1]:
import numpy as np
stock_A = np.array([
    [100, 105, 98],
    [102, 107, 101],
    [104, 110, 103],
    [103, 108, 102],
    [105, 112, 104]
])
stock_B = np.array([
    [99, 106, 97],
    [101, 108, 100],
    [105, 111, 102],
    [104, 107, 101],
    [106, 113, 105]
])
sum_matrix = stock_A + stock_B
diff_matrix = stock_A - stock_B
print("Stock A Matrix:\n", stock_A)
print("\nStock B Matrix:\n", stock_B)
print("\nElement-wise Sum of Stock A and B:\n", sum_matrix)
print("\nElement-wise Difference of Stock A and B (A-B):\n", diff_matrix)

Stock A Matrix:
 [[100 105  98]
 [102 107 101]
 [104 110 103]
 [103 108 102]
 [105 112 104]]

Stock B Matrix:
 [[ 99 106  97]
 [101 108 100]
 [105 111 102]
 [104 107 101]
 [106 113 105]]

Element-wise Sum of Stock A and B:
 [[199 211 195]
 [203 215 201]
 [209 221 205]
 [207 215 203]
 [211 225 209]]

Element-wise Difference of Stock A and B (A-B):
 [[ 1 -1  1]
 [ 1 -1  1]
 [-1 -1  1]
 [-1  1  1]
 [-1 -1 -1]]
